export const NIGERIAN_LOCATIONS: Record<string, string[]> = {
  Abuja: ['Abuja Municipal', 'Gwagwalada', 'Kuje', 'Bwari', 'Kwali', 'Abaji'],
  Lagos: [
    'Ikeja',
    'Lagos Island',
    'Lagos Mainland',
    'Surulere',
    'Yaba',
    'Maryland',
    'Alimosho',
    'Agege',
    'Mushin',
    'Oshodi',
    'Isolo',
    'Ikorodu',
    'Lekki',
    'Eti-Osa',
    'Ajah',
    'Badagry',
    'Epe',
  ],
  Rivers: ['Port Harcourt', 'Obio-Akpor', 'Bonny', 'Okrika', 'Eleme', 'Ikwerre'],
  Anambra: ['Awka', 'Onitsha', 'Nnewi', 'Ekwusigo', 'Idemili', 'Oyi'],
  Enugu: ['Enugu', 'Nsukka', 'Oji River', 'Udi', 'Awgu'],
  Edo: ['Benin City', 'Auchi', 'Ekpoma', 'Igarra', 'Uromi'],
  Delta: ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Abraka', 'Agbor'],
  Oyo: ['Ibadan', 'Ogbomosho', 'Oyo', 'Iseyin', 'Eruwa'],
  Ogun: ['Abeokuta', 'Ijebu Ode', 'Sagamu', 'Ota', 'Ilaro'],
  Kaduna: ['Kaduna', 'Zaria', 'Kafanchan', 'Saminaka'],
  Kano: ['Kano', 'Wudil', 'Gwarzo', 'Bichi'],
  Katsina: ['Katsina', 'Funtua', 'Daura'],
  Kwara: ['Ilorin', 'Offa', 'Jebba', 'Lafiagi'],
  Nasarawa: ['Lafia', 'Keffi', 'Karu', 'Akwanga'],
  Plateau: ['Jos', 'Bukuru', 'Pankshin', 'Shendam'],
  Benue: ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala'],
  Imo: ['Owerri', 'Orlu', 'Okigwe'],
  Abia: ['Umuahia', 'Aba', 'Arochukwu'],
  'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron'],
  'Cross River': ['Calabar', 'Ogoja', 'Ikom'],
  Ebonyi: ['Abakaliki', 'Afikpo', 'Onueke'],
  Bayelsa: ['Yenagoa', 'Brass', 'Sagbama'],
  Ekiti: ['Ado-Ekiti', 'Ikere', 'Efon-Alaaye'],
  Ondo: ['Akure', 'Ondo', 'Owo', 'Ikare'],
  Osun: ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede'],
  Kogi: ['Lokoja', 'Okene', 'Idah', 'Kabba'],
  Niger: ['Minna', 'Suleja', 'Bida', 'Kontagora'],
  Taraba: ['Jalingo', 'Wukari', 'Bali'],
  Adamawa: ['Yola', 'Mubi', 'Jimeta', 'Numan'],
  Bauchi: ['Bauchi', 'Azare', 'Misau'],
  Borno: ['Maiduguri', 'Biu', 'Monguno'],
  Yobe: ['Damaturu', 'Potiskum', 'Gashua'],
  Gombe: ['Gombe', 'Kumo', 'Billiri'],
  Jigawa: ['Dutse', 'Hadejia', 'Gumel'],
  Kebbi: ['Birnin Kebbi', 'Argungu', 'Yauri'],
  Sokoto: ['Sokoto', 'Tambuwal', 'Wurno'],
  Zamfara: ['Gusau', 'Kaura Namoda', 'Talata Mafara'],
};
